import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { generations, repos } from "@/lib/schema";
import { verifyDiffShareToken } from "@/lib/share-link";
import { DraftDiff } from "@/components/draft-diff";
import { Logo } from "@/components/logo";

export const dynamic = "force-dynamic";

/**
 * /share/diff/{token} — the shareable, unlisted draft-vs-published diff (P2.8).
 *
 * The token is the credential (HMAC over the generation id, lib/share-link.ts):
 * no session, no login, so a link pasted into the regeneration notification
 * email or a Slack thread opens for a teammate. Deliberately noindex — shared
 * draft content should never end up in a search index.
 */

type Props = { params: Promise<{ token: string }> };

async function fetchShareRow(token: string) {
  const generationId = verifyDiffShareToken(token);
  if (!generationId) return null;

  const [row] = await db
    .select({
      generationId: generations.id,
      status: generations.status,
      markdown: generations.markdown,
      publishedAt: generations.publishedAt,
      completedAt: generations.completedAt,
      repoFullName: repos.githubRepoFullName,
      defaultBranch: repos.defaultBranch,
      docsSubdomain: repos.docsSubdomain,
      publishedGenerationId: repos.publishedGenerationId,
    })
    .from(generations)
    .innerJoin(repos, eq(repos.id, generations.repoId))
    .where(eq(generations.id, generationId))
    .limit(1);

  if (!row || row.status !== "success" || !row.markdown) return null;

  let publishedMarkdown = "";
  if (row.publishedGenerationId && row.publishedGenerationId !== row.generationId) {
    const [published] = await db
      .select({ markdown: generations.markdown })
      .from(generations)
      .where(eq(generations.id, row.publishedGenerationId))
      .limit(1);
    publishedMarkdown = published?.markdown ?? "";
  }

  return { ...row, publishedMarkdown };
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { token } = await params;
  const row = await fetchShareRow(token);
  if (!row) return { title: "Shared diff not found — docloom", robots: { index: false } };
  return {
    title: `${row.repoFullName} — docs draft diff — docloom`,
    description: `Draft-vs-published documentation diff for ${row.repoFullName}.`,
    // Shared draft content: never indexed, never followed.
    robots: { index: false, follow: false },
  };
}

export default async function ShareDiffPage({ params }: Props) {
  const { token } = await params;
  const row = await fetchShareRow(token);
  if (!row) notFound();

  const isNew = row.publishedMarkdown.trim().length === 0;

  return (
    <div className="mx-auto w-full max-w-4xl flex-1 px-6 py-12">
      <header className="mb-6 border-b border-zinc-800 pb-6">
        <Link href="/" className="inline-block">
          <Logo markClassName="h-4 w-[19px]" wordmarkClassName="font-mono text-sm font-semibold tracking-tight" />
        </Link>
        <p className="mt-4 font-mono text-xs uppercase tracking-widest text-zinc-500">Shared diff</p>
        <h1 className="mt-1 font-mono text-xl font-semibold tracking-tight text-zinc-100">
          {row.repoFullName}
        </h1>
        <p className="mt-1 text-sm text-zinc-500">
          branch <span className="font-mono text-zinc-400">{row.defaultBranch}</span> ·{" "}
          {row.completedAt?.toLocaleString("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })}
          {row.publishedGenerationId ? (
            <>
              {" "}
              ·{" "}
              <Link href={`/docs/${row.docsSubdomain}`} className="font-mono text-zinc-300 hover:text-accent">
                view published docs
              </Link>
            </>
          ) : null}
        </p>
      </header>

      <div className="mb-4 rounded-lg border border-zinc-800 bg-zinc-900/50 px-4 py-3 text-sm text-zinc-400">
        {isNew
          ? "This repo doesn't have published docs yet — the whole draft is shown as an addition."
          : "This is the draft Docloom generated from the latest code, compared with what is currently published. Nothing is published until the owner approves it."}
      </div>

      <DraftDiff oldMarkdown={row.publishedMarkdown} newMarkdown={row.markdown ?? ""} defaultOpen />

      <p className="mt-8 font-mono text-[11px] text-zinc-600">
        unlisted link · not indexed · generated by docloom from source
      </p>
    </div>
  );
}
