import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { and, eq, isNotNull } from "drizzle-orm";
import ReactMarkdown from "react-markdown";
import { Logo } from "@/components/logo";
import remarkGfm from "remark-gfm";
import { db } from "@/lib/db";
import { generations, repos, users } from "@/lib/schema";
import { brandingRequired, effectivePlan } from "@/lib/billing";

export const dynamic = "force-dynamic";

/**
 * Public docs hosting, path-based: /docs/{docsSubdomain} serves the repo's
 * published generation. No auth (public docs), no draft content — only
 * generations promoted via the publish flow are ever rendered here.
 *
 * The wildcard-subdomain model ({subdomain}.docloom.app) needs the custom
 * domain on Cloudflare; this path-based host works on any deployment URL
 * today and the dashboard links switch automatically.
 */

const mdComponents = {
  table: (p: React.ComponentProps<"table">) => (
    <div className="my-4 overflow-x-auto">
      <table className="w-full border-collapse text-sm" {...p} />
    </div>
  ),
  th: (p: React.ComponentProps<"th">) => (
    <th className="border border-zinc-700 bg-zinc-800/60 px-3 py-1.5 text-left font-mono text-xs text-zinc-200" {...p} />
  ),
  td: (p: React.ComponentProps<"td">) => (
    <td className="border border-zinc-800 px-3 py-1.5 align-top text-zinc-300" {...p} />
  ),
  code: (p: React.ComponentProps<"code">) => (
    <code className="rounded bg-zinc-800 px-1 py-0.5 font-mono text-[12px] text-zinc-300" {...p} />
  ),
  pre: (p: React.ComponentProps<"pre">) => <pre className="my-3 overflow-x-auto" {...p} />,
};

function Markdown({ children }: { children: string }) {
  return (
    <ReactMarkdown remarkPlugins={[remarkGfm]} components={mdComponents}>
      {children}
    </ReactMarkdown>
  );
}

type Props = { params: Promise<{ subdomain: string }> };

async function fetchPublished(subdomain: string) {
  const [row] = await db
    .select({
      repoFullName: repos.githubRepoFullName,
      branch: repos.defaultBranch,
      markdown: generations.markdown,
      publishedAt: generations.publishedAt,
      plan: users.plan,
      dodoSubscriptionStatus: users.dodoSubscriptionStatus,
      dodoGraceUntil: users.dodoGraceUntil,
    })
    .from(repos)
    .innerJoin(generations, eq(generations.id, repos.publishedGenerationId))
    .innerJoin(users, eq(users.id, repos.userId))
    .where(and(eq(repos.docsSubdomain, subdomain), isNotNull(repos.publishedGenerationId)))
    .limit(1);
  return row ?? null;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { subdomain } = await params;
  const row = await fetchPublished(subdomain);
  if (!row) return { title: "Docs not found — docloom" };
  return {
    title: `${row.repoFullName} API docs — docloom`,
    description: `API documentation for ${row.repoFullName}, generated by docloom.`,
  };
}

export default async function DocsPage({ params }: Props) {
  const { subdomain } = await params;
  const row = await fetchPublished(subdomain);
  if (!row || !row.markdown) notFound();

  // Free plan: "Built with Docloom" branding on published pages. Paid plans:
  // no branding at all.
  const showBranding = brandingRequired(effectivePlan(row));

  return (
    <div className="mx-auto w-full max-w-3xl flex-1 px-6 py-12">
      <header className="mb-8 border-b border-zinc-800 pb-6">
        <Logo
          markClassName="h-4 w-[19px]"
          wordmarkClassName="font-mono text-sm font-semibold tracking-tight"
        />
        <p className="mt-4 font-mono text-xs uppercase tracking-widest text-zinc-500">
          API documentation
        </p>
        <h1 className="mt-1 font-mono text-xl font-semibold tracking-tight text-zinc-100">
          {row.repoFullName}
        </h1>
        <p className="mt-1 text-sm text-zinc-500">
          branch <span className="font-mono text-zinc-400">{row.branch}</span> · published{" "}
          {row.publishedAt?.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
        </p>
      </header>

      <article>
        <Markdown>{row.markdown}</Markdown>
      </article>

      {showBranding ? (
        <footer className="mt-12 border-t border-zinc-800 pt-6">
          <div className="flex justify-center">
            <Link
              href="/"
              className="inline-flex items-center gap-2 rounded-full border border-zinc-800 bg-zinc-900/60 px-4 py-2 text-xs text-zinc-400 transition-colors hover:border-zinc-600 hover:text-zinc-200"
            >
              <Logo markClassName="h-3 w-[14px]" />
              <span>
                Built with <span className="font-medium text-zinc-200">Docloom</span>
              </span>
            </Link>
          </div>
        </footer>
      ) : null}
    </div>
  );
}
