import type { Metadata } from "next";
import { ComparisonPage, type ComparisonRow, type ComparisonSection } from "@/components/comparison-page";

export const metadata: Metadata = {
  title: "Mintlify alternative for source-generated API docs",
  description:
    "How Docloom compares with Mintlify: Mintlify is a docs platform you author in MDX; Docloom generates the API reference from your Next.js route handlers and Zod schemas.",
  alternates: { canonical: "/vs/mintlify" },
};

const ROWS: ComparisonRow[] = [
  {
    dimension: "Content source",
    docloom: "Generated from your source code (TypeScript AST + Zod), with AI-written descriptions.",
    other: "Authored by your team in MDX.",
  },
  {
    dimension: "API reference",
    docloom: "Extracted from route handlers: endpoints, request bodies, response shapes, query and header inputs.",
    other: "Written or generated by you, or imported from an OpenAPI document.",
  },
  {
    dimension: "Guides and prose",
    docloom: "Not the focus — Docloom produces the API reference.",
    other: "Full support for guides, tutorials, custom pages and components.",
  },
  {
    dimension: "Hosting",
    docloom: "Included: a docs site on your subdomain, regenerated on merge.",
    other: "Included: hosted platform with custom domains.",
  },
  {
    dimension: "Extras",
    docloom: "Diff-before-publish, auto-regenerate on merge, coverage notes for fields it cannot prove.",
    other: "Search, AI assistant, navigation, versioning and analytics.",
  },
  {
    dimension: "Maintenance",
    docloom: "Re-reads the source each run; there is no reference content to keep in sync.",
    other: "You keep the MDX in sync with the code.",
  },
];

const SECTIONS: ComparisonSection[] = [
  {
    heading: "When Mintlify is the better fit",
    body: "If you need a full documentation site — guides, tutorials, custom components, search, versioning and an AI assistant — a documentation platform is the right tool, and Mintlify is built for exactly that.",
  },
  {
    heading: "When Docloom is the better fit",
    body: "If the recurring pain is the API reference going stale, Docloom derives it from the source so it tracks the code without manual updates, and marks anything it cannot prove instead of inventing it.",
  },
  {
    heading: "Using them together",
    body: "A common setup is a docs platform for the prose and Docloom for the generated API reference. Nothing about Docloom requires you to replace an existing docs site.",
  },
];

export default function MintlifyComparisonPage() {
  return (
    <ComparisonPage
      eyebrow="Comparison"
      title="Docloom vs Mintlify"
      otherLabel="Mintlify"
      intro="Mintlify is a documentation platform: you author pages in MDX and it hosts them with navigation, search and an AI assistant. Docloom generates an API reference from your Next.js route handlers and Zod schemas and hosts it. The two overlap at the hosted-docs layer and differ in where the content comes from."
      rows={ROWS}
      sections={SECTIONS}
      playgroundRepo="calcom/cal.com"
      ctaId="vs_mintlify_playground"
    />
  );
}
