import Link from "next/link";
import { LogoMark } from "./logo";

/**
 * Free-tier docs badge: small, theme-aware, links to the playground for the same
 * repo so a free user can try the no-signup generator on it.
 *
 * Uses currentColor (LogoMark weft) + accent (LogoMark warp), so it inherits the
 * surrounding text colour and reads correctly on any surface.
 */
export function DocloomBadge({
  owner,
  repo,
  className = "",
}: {
  owner: string;
  repo: string;
  className?: string;
}) {
  const playgroundUrl = `/playground?repo=${encodeURIComponent(`${owner}/${repo}`)}`;
  return (
    <Link
      href={playgroundUrl}
      className={`inline-flex items-center gap-1.5 rounded-full border border-zinc-700 bg-zinc-900/60 px-2 py-0.5 text-[11px] text-zinc-400 transition-colors hover:border-zinc-600 hover:text-zinc-200 ${className}`}
    >
      <LogoMark className="h-3 w-3.5" />
      <span>Generated by Docloom</span>
    </Link>
  );
}
